/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ConcentRouteImport } from './routes/concent'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileConnectedAppsRouteImport } from './routes/profile/connected-apps'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminCredentialsRouteImport } from './routes/admin/credentials'
import { Route as AuthedDevRouteImport } from './routes/_authed/dev'
import { Route as AuthedDevIndexRouteImport } from './routes/_authed/dev/index'
import { Route as ApiUserDataUserIdRouteImport } from './routes/api.user-data.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAdminDeleteUserRouteImport } from './routes/api/admin/delete-user'
import { Route as AuthedDevAppsNewRouteImport } from './routes/_authed/dev/apps.new'
import { Route as AuthedDevAppIdRouteImport } from './routes/_authed/dev/app.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcentRoute = ConcentRouteImport.update({
  id: '/concent',
  path: '/concent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileConnectedAppsRoute = ProfileConnectedAppsRouteImport.update({
  id: '/connected-apps',
  path: '/connected-apps',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/admin/credentials',
  path: '/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDevRoute = AuthedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevIndexRoute = AuthedDevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDevRoute,
} as any)
const ApiUserDataUserIdRoute = ApiUserDataUserIdRouteImport.update({
  id: '/api/user-data/$userId',
  path: '/api/user-data/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteUserRoute = ApiAdminDeleteUserRouteImport.update({
  id: '/api/admin/delete-user',
  path: '/api/admin/delete-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDevAppsNewRoute = AuthedDevAppsNewRouteImport.update({
  id: '/apps/new',
  path: '/apps/new',
  getParentRoute: () => AuthedDevRoute,
} as any)
const AuthedDevAppIdRoute = AuthedDevAppIdRouteImport.update({
  id: '/app/$id',
  path: '/app/$id',
  getParentRoute: () => AuthedDevRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concent': typeof ConcentRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/dev': typeof AuthedDevRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/connected-apps': typeof ProfileConnectedAppsRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user-data/$userId': typeof ApiUserDataUserIdRoute
  '/dev/': typeof AuthedDevIndexRoute
  '/dev/app/$id': typeof AuthedDevAppIdRoute
  '/dev/apps/new': typeof AuthedDevAppsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concent': typeof ConcentRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/connected-apps': typeof ProfileConnectedAppsRoute
  '/profile': typeof ProfileIndexRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user-data/$userId': typeof ApiUserDataUserIdRoute
  '/dev': typeof AuthedDevIndexRoute
  '/dev/app/$id': typeof AuthedDevAppIdRoute
  '/dev/apps/new': typeof AuthedDevAppsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/concent': typeof ConcentRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/_authed/dev': typeof AuthedDevRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/connected-apps': typeof ProfileConnectedAppsRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user-data/$userId': typeof ApiUserDataUserIdRoute
  '/_authed/dev/': typeof AuthedDevIndexRoute
  '/_authed/dev/app/$id': typeof AuthedDevAppIdRoute
  '/_authed/dev/apps/new': typeof AuthedDevAppsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concent'
    | '/consent'
    | '/login'
    | '/profile'
    | '/dev'
    | '/admin/credentials'
    | '/admin/users'
    | '/profile/connected-apps'
    | '/profile/'
    | '/api/admin/delete-user'
    | '/api/auth/$'
    | '/api/user-data/$userId'
    | '/dev/'
    | '/dev/app/$id'
    | '/dev/apps/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concent'
    | '/consent'
    | '/login'
    | '/admin/credentials'
    | '/admin/users'
    | '/profile/connected-apps'
    | '/profile'
    | '/api/admin/delete-user'
    | '/api/auth/$'
    | '/api/user-data/$userId'
    | '/dev'
    | '/dev/app/$id'
    | '/dev/apps/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/concent'
    | '/consent'
    | '/login'
    | '/profile'
    | '/_authed/dev'
    | '/admin/credentials'
    | '/admin/users'
    | '/profile/connected-apps'
    | '/profile/'
    | '/api/admin/delete-user'
    | '/api/auth/$'
    | '/api/user-data/$userId'
    | '/_authed/dev/'
    | '/_authed/dev/app/$id'
    | '/_authed/dev/apps/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ConcentRoute: typeof ConcentRoute
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiAdminDeleteUserRoute: typeof ApiAdminDeleteUserRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserDataUserIdRoute: typeof ApiUserDataUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concent': {
      id: '/concent'
      path: '/concent'
      fullPath: '/concent'
      preLoaderRoute: typeof ConcentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/connected-apps': {
      id: '/profile/connected-apps'
      path: '/connected-apps'
      fullPath: '/profile/connected-apps'
      preLoaderRoute: typeof ProfileConnectedAppsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/admin/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dev': {
      id: '/_authed/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthedDevRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dev/': {
      id: '/_authed/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthedDevIndexRouteImport
      parentRoute: typeof AuthedDevRoute
    }
    '/api/user-data/$userId': {
      id: '/api/user-data/$userId'
      path: '/api/user-data/$userId'
      fullPath: '/api/user-data/$userId'
      preLoaderRoute: typeof ApiUserDataUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-user': {
      id: '/api/admin/delete-user'
      path: '/api/admin/delete-user'
      fullPath: '/api/admin/delete-user'
      preLoaderRoute: typeof ApiAdminDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dev/apps/new': {
      id: '/_authed/dev/apps/new'
      path: '/apps/new'
      fullPath: '/dev/apps/new'
      preLoaderRoute: typeof AuthedDevAppsNewRouteImport
      parentRoute: typeof AuthedDevRoute
    }
    '/_authed/dev/app/$id': {
      id: '/_authed/dev/app/$id'
      path: '/app/$id'
      fullPath: '/dev/app/$id'
      preLoaderRoute: typeof AuthedDevAppIdRouteImport
      parentRoute: typeof AuthedDevRoute
    }
  }
}

interface AuthedDevRouteChildren {
  AuthedDevIndexRoute: typeof AuthedDevIndexRoute
  AuthedDevAppIdRoute: typeof AuthedDevAppIdRoute
  AuthedDevAppsNewRoute: typeof AuthedDevAppsNewRoute
}

const AuthedDevRouteChildren: AuthedDevRouteChildren = {
  AuthedDevIndexRoute: AuthedDevIndexRoute,
  AuthedDevAppIdRoute: AuthedDevAppIdRoute,
  AuthedDevAppsNewRoute: AuthedDevAppsNewRoute,
}

const AuthedDevRouteWithChildren = AuthedDevRoute._addFileChildren(
  AuthedDevRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDevRoute: typeof AuthedDevRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDevRoute: AuthedDevRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ProfileRouteChildren {
  ProfileConnectedAppsRoute: typeof ProfileConnectedAppsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileConnectedAppsRoute: ProfileConnectedAppsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ConcentRoute: ConcentRoute,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiAdminDeleteUserRoute: ApiAdminDeleteUserRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserDataUserIdRoute: ApiUserDataUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
