export const userDataTypeList = [
    "rut",
    "email",
    "phone",
    "first_name",
    "last_name",
    "date_of_birth",
    "nationality",
    "marital_status",
    "address",
    "gender",
    "profession",
    "income",
    "job_position",
] as const;
